version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      
  build:
    commands:
      - echo Building the Flask Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-app-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-app-repo:latest

artifacts:
  files:
    - imagedefinitions.json
