version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "flask-ecs-fargate-repo"  # Name of your ECR repository
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
      # Replace 'us-east-1' with your AWS region and '123456789012' with your AWS account ID

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # Replace 'us-east-1' and '123456789012' with your AWS region and account ID

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # Replace 'us-east-1' and '123456789012' with your AWS region and account ID
      - echo Writing image definitions file...
      - printf '[{"name":"flask-app","imageUri":"%s"}]' 123456789012.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      # Replace 'us-east-1' and '123456789012' with your AWS region and account ID

artifacts:
  files:
    - imagedefinitions.json
